import os
import json
from io import BytesIO
from PIL import Image
import streamlit as st
import matplotlib.pyplot as plt
import datetime

from utils.prediction import predict_image_class
from utils.disease_info import disease_details

st.set_page_config(page_title='Plant Disease Classifier', layout='wide')

# ------------------------------------------------
# PDF REPORT FUNCTION (ONLY NEW ADDITION)
# ------------------------------------------------
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def generate_pdf_report(disease_name, confidence, info):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    width, height = letter
    y = height - 50

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "PLANT DISEASE DIAGNOSIS REPORT")
    y -= 30

    c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Disease Name: {disease_name}")
    y -= 20
    c.drawString(50, y, f"Confidence: {confidence:.2f}%")
    y -= 20
    c.drawString(50, y, f"Generated On: {datetime.datetime.now()}")
    y -= 30

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Symptoms:")
    y -= 20
    c.setFont("Helvetica", 12)
    for s in info["symptoms"]:
        c.drawString(70, y, f"- {s}")
        y -= 18

    y -= 10
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Causes:")
    y -= 20
    c.setFont("Helvetica", 12)
    for c_item in info["causes"]:
        c.drawString(70, y, f"- {c_item}")
        y -= 18

    y -= 10
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Remedies:")
    y -= 20
    c.setFont("Helvetica", 12)
    for r in info["remedies"]:
        c.drawString(70, y, f"- {r}")
        y -= 18

    y -= 10
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Prevention:")
    y -= 20
    c.setFont("Helvetica", 12)
    for p in info["prevention"]:
        c.drawString(70, y, f"- {p}")
        y -= 18

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# -----------------------------------------------


# ----------------------------
# REPORT GENERATION FUNCTION (unchanged)
# ----------------------------
def generate_report(disease_name, confidence, info):
    report = []
    report.append("PLANT DISEASE DIAGNOSIS REPORT")
    report.append("---------------------------------------")
    report.append(f"Disease Name: {disease_name}")
    report.append(f"Prediction Confidence: {confidence:.2f}%")
    report.append(f"Generated On: {datetime.datetime.now()}")
    
    report.append("\nSymptoms:")
    for s in info["symptoms"]:
        report.append(f" - {s}")

    report.append("\nCauses:")
    for c in info["causes"]:
        report.append(f" - {c}")

    report.append("\nRemedies:")
    for r in info["remedies"]:
        report.append(f" - {r}")

    report.append("\nPrevention:")
    for p in info["prevention"]:
        report.append(f" - {p}")

    report.append("\n---------------------------------------")
    report.append("Generated by Plant Disease Predictor App")

    return "\n".join(report)


# ----------------------------
# PATHS & MODEL LOADING
# ----------------------------
WORKING_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(WORKING_DIR, 'trained_model', 'plant_disease_prediction_model.h5')
CLASS_PATH = os.path.join(WORKING_DIR, 'trained_model', 'class_indices.json')


@st.cache_resource
def load_model(path):
    import tensorflow as tf
    return tf.keras.models.load_model(path)


@st.cache_data
def load_class_indices(path):
    with open(path, 'r') as f:
        return json.load(f)


# Load model
try:
    model = load_model(MODEL_PATH)
except Exception as e:
    st.error(f"Could not load model at {MODEL_PATH}: {e}")
    st.stop()

# Load class indices
try:
    class_indices = load_class_indices(CLASS_PATH)
except Exception as e:
    st.error(f"Could not load class indices at {CLASS_PATH}: {e}")
    st.stop()


# ----------------------------
# UI LAYOUT
# ----------------------------
st.title("🌿 Plant Disease Classifier (Quick KB)")
st.write("Upload one clear leaf image. The app shows top-3 predictions with scores and a short description for the top result.")

col1, col2 = st.columns([1, 2])

with col1:
    uploaded_file = st.file_uploader("Upload leaf image", type=['jpg', 'jpeg', 'png'])
    st.write("")
    st.markdown("**Model info**")
    st.text(f"Model: {os.path.basename(MODEL_PATH)}")
    st.text(f"Classes: {len(class_indices)}")

with col2:
    st.markdown("**Tips for good prediction**")
    st.write("- Crop so the leaf fills most of the image.")
    st.write("- Good lighting and focused image helps.")
    st.write("- If confidence is low, try multiple angles.")


# ----------------------------
# PREDICTION SECTION
# ----------------------------
if uploaded_file is not None:
    image = Image.open(BytesIO(uploaded_file.read())).convert('RGB')
    st.image(image, caption='Uploaded image', use_column_width=True)

    if st.button("🔍 Predict"):
        with st.spinner("Predicting..."):
            try:
                top1, top1_score, top3 = predict_image_class(model, uploaded_file, class_indices)

                st.success(f"**Top prediction:** {top1} — {top1_score * 100:.2f}%")

                # ----------- TOP-3 BAR CHART -----------
                labels = [p['class'] for p in top3]
                scores = [p['score'] * 100 for p in top3]

                fig, ax = plt.subplots(figsize=(6, 3))
                y_pos = range(len(labels))
                ax.barh(y_pos[::-1], scores)
                ax.set_yticks(y_pos[::-1])
                ax.set_yticklabels(labels)
                ax.set_xlabel('Probability (%)')
                ax.set_title('Top-3 Predictions')
                st.pyplot(fig)

                st.markdown('---')

                # ----------- DISPLAY DISEASE INFO -----------
                info = disease_details.get(top1, None)
                if info:
                    st.header(info.get('display_name', top1))
                    
                    st.subheader("Symptoms")
                    for s in info["symptoms"]:
                        st.markdown(f"- {s}")

                    st.subheader("Causes")
                    for c in info["causes"]:
                        st.markdown(f"- {c}")

                    st.subheader("Remedies")
                    for r in info["remedies"]:
                        st.markdown(f"- {r}")

                    st.subheader("Prevention")
                    for p in info["prevention"]:
                        st.markdown(f"- {p}")

                    # ----------- PDF REPORT DOWNLOAD BUTTON -----------
                    pdf_file = generate_pdf_report(top1, top1_score * 100, info)

                    st.download_button(
                        label="📄 Download Report (PDF)",
                        data=pdf_file,
                        file_name=f"{top1}_report.pdf",
                        mime="application/pdf"
                    )

                else:
                    st.warning("Short disease info not available for this class.")

            except Exception as e:
                st.error(f"Prediction failed: {e}")
